/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sibka;

import java.util.Random;

/**
 *
 * @author jan
 */


public class hra extends javax.swing.JPanel {
    int pokus = 0;
    int dalsi = 0;
    boolean konec = false;
    String[] poleslovo = new String[10];
    String[] polehled = new String[10];
    /**
     * Creates new form hra
     */
    String tajenka = "";
            //přidat ho
            int blbec = 0;
        String[] slova={"generátor","malůvka","chaloupka","rozinka","mazání","štír","konektor","asfalt","naběračka","úsvit","brouček","pařát","převod","zámek","černoch","radiátor","důvěra","mrak","deprese","krumpáč","kabát","volnost","matka","šerednost","krb","malování","náskok","schodiště","striptér","artefakt","kominík","monopol","krocan","letadlo","plechovka","zákazník","beruška","jabloň","seznam","vážka","srub","bonbon","zelenooká","kasa","vládce","buzola","horda","letenka","klavíristka","sýr"};
        Random t=new Random();
        int randomcislo=t.nextInt(slova.length);
        String slovicko = slova[randomcislo];
        String slovomez = "";

        
    public hra() {
        if(dalsi == 1){
      
        }
        initComponents();
        int delkanom = slovicko.length();
        int delka2 = 2*slovicko.length();
        System.out.println("delka2: " + delka2);
        int pl = 0;
        for(int i = 0; i < delka2; i++){
            if(pl >= delkanom){
                
            }else{
            String znak = slovicko.substring(pl, pl+1);
            if(delka2%2 == 0){
                
                 System.out.println("sudý");
                slovomez = slovomez + znak;
                pl++;
            }else{
                slovomez = slovomez + " ";
            }
          }  
        }
        int deeeelka = slovomez.length();
        
        System.out.println("slovomez: " + slovomez);
        
        poleslovo = new String[deeeelka];
        polehled = new String[deeeelka];
        for(int k = 0; k < poleslovo.length; k++){
            poleslovo[k] = slovomez.substring(k, k+1);
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        odeslat = new javax.swing.JButton();
        hadane = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Písmo které chcete hádat:");

        jTextField1.setText("PÍSMENKO");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        odeslat.setText("ODESLAT");
        odeslat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odeslatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216)
                .addComponent(odeslat, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odeslat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        hadane.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        hadane.setText("text");
        System.out.println(slovicko);
        int delka = slovicko.length();

        for(int i = 0; i < delka; i++){
            tajenka = tajenka+" _";
        }
        hadane.setText(tajenka);

        jButton1.setText("menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hadane, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(44, 44, 44)
                        .addComponent(hadane, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       hlavniwindow.hlavnipanel.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void odeslatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odeslatActionPerformed
        String tip = String.valueOf(jTextField1.getText());
        String pismeno = tip.substring(0,1);
        pismeno = pismeno.toLowerCase();
        System.out.println(pismeno);
        
        int i;
        int pocetznk = 0;
        
        int delka3 = slovicko.length();
        if(dalsi == 1){
            
        }
        for(int u = 0; u < poleslovo.length; u++){
            String znak = tajenka.substring(u,u+1);
            if(znak.equals(pismeno)){
            pocetznk = pocetznk+1;
            polehled[u] = pismeno;
            System.out.println("TADY");
            }  
        }
        String tajenkafin = "";
        System.out.println("počet znaků: " + pocetznk);
        
        for(int u = 0; u < slovomez.length(); u++){
             String znak = slovomez.substring(u,u+1);
             System.out.println("znak: " + znak);
             System.out.println("smovomez: " + slovomez);
             if(znak.equals(pismeno)){
             tajenkafin = tajenkafin + pismeno; 
             polehled[u] = pismeno;
             System.out.println("rovná se");
             pocetznk++;
             }else{
             tajenkafin = tajenkafin + " _";   
             System.out.println("nerovná se");
             
             }
        }
        
        if(pocetznk == 0){
            pokus++;
            switch(pokus){
            
                case 1:
                    jLabel1.setIcon(new javax.swing.ImageIcon("./src/images/1.png"));
                break;
                case 2:
                    jLabel1.setIcon(new javax.swing.ImageIcon("./src/images/2.png"));
                break;
                case 3:
                    jLabel1.setIcon(new javax.swing.ImageIcon("./src/images/3.png"));
                break;
                case 4:
                    jLabel1.setIcon(new javax.swing.ImageIcon("./src/images/4.png"));
                break;
                case 5:
                    jLabel1.setIcon(new javax.swing.ImageIcon("./src/images/5.png"));
                break;
                case 6:
                    jLabel1.setIcon(new javax.swing.ImageIcon("./src/images/6.png"));
                break;
                case 7:
                    jLabel1.setIcon(new javax.swing.ImageIcon("./src/images/7.png"));
                break;
                case 8:
                    jLabel1.setIcon(new javax.swing.ImageIcon("./src/images/8.png"));
                break;
                case 9:
                    jLabel1.setIcon(new javax.swing.ImageIcon("./src/images/9.png"));
                break;
                case 10:
                    jLabel1.setIcon(new javax.swing.ImageIcon("./src/images/10.png"));
                break; 
                case 11:
                    jLabel1.setIcon(new javax.swing.ImageIcon("./src/images/11.png"));
                 odeslat.setVisible(false);
                 konec = true;
                 jTextField1.setVisible(false);
                 jLabel2.setVisible(false);
                break;
                 
            }
        }
        
        String vysledek = "";
        for(int u = 0; u < polehled.length; u++){
           if(polehled[u] != null){
               System.out.println(polehled[u]);
             vysledek = vysledek + polehled[u];  
           }else{
               System.out.println(polehled[u]);
             vysledek = vysledek + " _"; 
           } 
        }
        System.out.println(vysledek);
        System.out.println(tajenkafin);
        hadane.setText(vysledek);
        
        if(konec == true){
            hadane.setText(slovicko);
            
        }
        
        i = slovomez.indexOf(pismeno);
        
    }//GEN-LAST:event_odeslatActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hadane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton odeslat;
    // End of variables declaration//GEN-END:variables
}
